[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm run deploy:railway"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "auto-picklist-app"

[services.build]
buildCommand = "npm ci && npm run build"

[services.deploy]
startCommand = "npm run deploy:railway"

[[services]]
name = "postgres"
source = "postgresql"

[services.database]
postgresqlDatabase = "autopicklist"